GET http://localhost:3000/users

###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users
content-type: application/json

{
  "email": "Scottgerald@gmail.com",
  "username": "Sgerald231",
  "bracket_made": false,
  "password": "password",
  "password_confirmation": "password"
}

###
PATCH http://localhost:3000/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2NTE5NDQ4MTZ9.KMMmpZz3slr_Bhuy7K_M4sZ2VYdthXOCC_8oir5PfuU
content-type: application/json

{
  "username": "G-eazy902"
}

###
DELETE http://localhost:3000/users/3

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Scottgerald@gmail.com",
  "password_digest": "password"
}


###
GET https://api.challonge.com/v1/
Authorization: Bearer 
Content-Type: application/json


###
GET http://localhost:3000/games

###

GET http://localhost:3000/user_games