GET http://localhost:3000/users

###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users
content-type: application/json

{
  "email": "Scottgerald@gmail.com",
  "username": "Sgerald231",
  "bracket_made": false,
  "password": "password",
  "password_confirmation": "password"
}

###
PATCH http://localhost:3000/users/4
Authorization: const API_KEY = process.env.REACT_APP_WEATHER_API_KEY;
content-type: application/json

{
  "username": "BendinLikeMaria11"
}

###
DELETE http://localhost:3000/users/3

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Scottgerald@gmail.com",
  "password_digest": "password"
}


###
GET https://api.challonge.com/v1/
Authorization: Bearer lfnFHKeHL47NKzPaaLTVvr1oB3g7wyRkc0XxVlvk
Content-Type: application/json